---
# Setup variables
- include: variables.yml

- name: "Disable SELinux :("
  selinux:
    state: disabled

- name: "Stop iptables :("
  service:
    name: "{{ __firewall_service }}"
    state: stopped
  ignore_errors: yes

- name: "Disable iptables :("
  service:
    name: "{{ __firewall_service }}"
    enabled: no
  ignore_errors: yes

- name: Template kube RPM repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install optional packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nano

# The kube_version variable can be from this list...
# That is, the `yum search kubelet --showduplicates`
# (as of 8/9/17)
# 
# e.g. you would use "1.6.6-0" for kube 1.6.6
#
# kubelet-1.5.4-0.x86_64 : Container cluster management
# kubelet-1.6.0-0.x86_64 : Container cluster management
# kubelet-1.6.1-0.x86_64 : Container cluster management
# kubelet-1.6.2-0.x86_64 : Container cluster management
# kubelet-1.6.3-0.x86_64 : Container cluster management
# kubelet-1.6.4-0.x86_64 : Container cluster management
# kubelet-1.6.5-0.x86_64 : Container cluster management
# kubelet-1.6.6-0.x86_64 : Container cluster management
# kubelet-1.6.7-0.x86_64 : Container cluster management
# kubelet-1.7.0-0.x86_64 : Container cluster management
# kubelet-1.7.1-0.x86_64 : Container cluster management
# kubelet-1.7.2-0.x86_64 : Container cluster management
# kubelet-1.7.3-1.x86_64 : Container cluster management
# kubelet-1.7.3-1.x86_64 : Container cluster management

- name: Default kube version fact
  set_fact: 
    kube_version_parameter: ""

- name: Default kube version fact
  set_fact: 
    kube_version_parameter: "-{{ kube_version }}"
  when: kube_version is defined

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubectl{{ kube_version_parameter }}
    - kubelet{{ kube_version_parameter }}
    - kubeadm{{ kube_version_parameter }}
    - kubernetes-cni



- name: Install docker (when using docker mode)
  package:
    name: "docker"
    state: present
  when: "container_runtime == 'docker'"

- name: Include kube 1.6.0 work-around
  include: kube-16-workaround.yml
  when: kube_16_workaround

- name: Remove default kubeadm.conf ExecStart
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: 'KUBELET_EXTRA_ARGS$'
    state: absent

- name: Add custom kubeadm.conf ExecStart
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: 'systemd$'
    line: 'ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_EXTRA_ARGS --cgroup-driver=systemd'

- name: Reload systemd units after changing 10-kubeadm.conf
  command: systemctl daemon-reload

- name: Start and enable kubelet
  service:
    name: "kubelet"
    state: restarted
    enabled: yes

- name: Start docker when appropriate
  service:
    name: "docker"
    state: restarted
    enabled: yes
  when: "container_runtime == 'docker'"
